// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Order struct {
	ID           string          `json:"id"`
	UserID       string          `json:"user_id"`
	RestaurantID string          `json:"restaurant_id"`
	Status       string          `json:"status"`
	TotalAmount  float64         `json:"total_amount"`
	Items        json.RawMessage `json:"items"`
	CourierID    sql.NullString  `json:"courier_id"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}
