// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: orders.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const assignCourier = `-- name: AssignCourier :execrows
UPDATE orders
SET courier_id = $1, status = $2, updated_at = NOW()
WHERE id = $3
`

type AssignCourierParams struct {
	CourierID sql.NullString `json:"courier_id"`
	Status    string         `json:"status"`
	ID        string         `json:"id"`
}

func (q *Queries) AssignCourier(ctx context.Context, arg AssignCourierParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, assignCourier, arg.CourierID, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders (id, user_id, restaurant_id, status, total_amount, items, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateOrderParams struct {
	ID           string          `json:"id"`
	UserID       string          `json:"user_id"`
	RestaurantID string          `json:"restaurant_id"`
	Status       string          `json:"status"`
	TotalAmount  float64         `json:"total_amount"`
	Items        json.RawMessage `json:"items"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.ExecContext(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.RestaurantID,
		arg.Status,
		arg.TotalAmount,
		arg.Items,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, restaurant_id, status, total_amount, items, courier_id, created_at, updated_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RestaurantID,
		&i.Status,
		&i.TotalAmount,
		&i.Items,
		&i.CourierID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, restaurant_id, status, total_amount, items, courier_id, created_at, updated_at
FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByUser(ctx context.Context, userID string) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RestaurantID,
			&i.Status,
			&i.TotalAmount,
			&i.Items,
			&i.CourierID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :execrows
UPDATE orders
SET status = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateOrderStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateOrderStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
