// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: menu_items.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createMenuItem = `-- name: CreateMenuItem :exec
INSERT INTO menu_items (id, restaurant_id, name, description, price)
VALUES ($1, $2, $3, $4, $5)
`

type CreateMenuItemParams struct {
	ID           string         `json:"id"`
	RestaurantID string         `json:"restaurant_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Price        float64        `json:"price"`
}

func (q *Queries) CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) error {
	_, err := q.db.ExecContext(ctx, createMenuItem,
		arg.ID,
		arg.RestaurantID,
		arg.Name,
		arg.Description,
		arg.Price,
	)
	return err
}

const getMenuItems = `-- name: GetMenuItems :many
SELECT id, restaurant_id, name, description, price, available
FROM menu_items
WHERE restaurant_id = $1
  AND id = ANY ($2::text[])
  AND available = TRUE
`

type GetMenuItemsParams struct {
	RestaurantID string   `json:"restaurant_id"`
	Ids          []string `json:"ids"`
}

func (q *Queries) GetMenuItems(ctx context.Context, arg GetMenuItemsParams) ([]MenuItem, error) {
	rows, err := q.db.QueryContext(ctx, getMenuItems, arg.RestaurantID, pq.Array(arg.Ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuItem{}
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Available,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuByRestaurant = `-- name: ListMenuByRestaurant :many
SELECT id, restaurant_id, name, description, price, available
FROM menu_items
WHERE restaurant_id = $1
`

func (q *Queries) ListMenuByRestaurant(ctx context.Context, restaurantID string) ([]MenuItem, error) {
	rows, err := q.db.QueryContext(ctx, listMenuByRestaurant, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuItem{}
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Available,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
