// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: restaurants.sql

package db

import (
	"context"
)

const countRestaurants = `-- name: CountRestaurants :one
SELECT COUNT(*)::bigint AS count
FROM restaurants
`

func (q *Queries) CountRestaurants(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRestaurants)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRestaurant = `-- name: CreateRestaurant :exec
INSERT INTO restaurants (id, name, address, is_open)
VALUES ($1, $2, $3, $4)
`

type CreateRestaurantParams struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Address string `json:"address"`
	IsOpen  bool   `json:"is_open"`
}

func (q *Queries) CreateRestaurant(ctx context.Context, arg CreateRestaurantParams) error {
	_, err := q.db.ExecContext(ctx, createRestaurant,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.IsOpen,
	)
	return err
}

const getRestaurant = `-- name: GetRestaurant :one
SELECT id, name, address, is_open, open_from, open_to
FROM restaurants
WHERE id = $1
`

func (q *Queries) GetRestaurant(ctx context.Context, id string) (Restaurant, error) {
	row := q.db.QueryRowContext(ctx, getRestaurant, id)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.IsOpen,
		&i.OpenFrom,
		&i.OpenTo,
	)
	return i, err
}

const listRestaurants = `-- name: ListRestaurants :many
SELECT id, name, address, is_open, open_from, open_to
FROM restaurants
`

func (q *Queries) ListRestaurants(ctx context.Context) ([]Restaurant, error) {
	rows, err := q.db.QueryContext(ctx, listRestaurants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Restaurant{}
	for rows.Next() {
		var i Restaurant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.IsOpen,
			&i.OpenFrom,
			&i.OpenTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
