// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: addresses.sql

package db

import (
	"context"
)

const createAddress = `-- name: CreateAddress :exec
INSERT INTO addresses (id, user_id, label, street, city, latitude, longitude, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAddressParams struct {
	ID        string  `json:"id"`
	UserID    string  `json:"user_id"`
	Label     string  `json:"label"`
	Street    string  `json:"street"`
	City      string  `json:"city"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
	IsDefault bool    `json:"is_default"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) error {
	_, err := q.db.ExecContext(ctx, createAddress,
		arg.ID,
		arg.UserID,
		arg.Label,
		arg.Street,
		arg.City,
		arg.Latitude,
		arg.Longitude,
		arg.IsDefault,
	)
	return err
}

const listAddressesByUser = `-- name: ListAddressesByUser :many
SELECT id, user_id, label, street, city, latitude, longitude, is_default
FROM addresses
WHERE user_id = $1
`

func (q *Queries) ListAddressesByUser(ctx context.Context, userID string) ([]Address, error) {
	rows, err := q.db.QueryContext(ctx, listAddressesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Address{}
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.Street,
			&i.City,
			&i.Latitude,
			&i.Longitude,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
