// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type Payment struct {
	ID                  string         `json:"id"`
	OrderID             string         `json:"order_id"`
	Amount              float64        `json:"amount"`
	Method              string         `json:"method"`
	Status              string         `json:"status"`
	TransactionID       sql.NullString `json:"transaction_id"`
	RefundTransactionID sql.NullString `json:"refund_transaction_id"`
	RefundReason        sql.NullString `json:"refund_reason"`
	CreatedAt           time.Time      `json:"created_at"`
}
