// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: payments.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createPayment = `-- name: CreatePayment :exec
INSERT INTO payments (id, order_id, amount, method, status, transaction_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreatePaymentParams struct {
	ID            string         `json:"id"`
	OrderID       string         `json:"order_id"`
	Amount        float64        `json:"amount"`
	Method        string         `json:"method"`
	Status        string         `json:"status"`
	TransactionID sql.NullString `json:"transaction_id"`
	CreatedAt     time.Time      `json:"created_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) error {
	_, err := q.db.ExecContext(ctx, createPayment,
		arg.ID,
		arg.OrderID,
		arg.Amount,
		arg.Method,
		arg.Status,
		arg.TransactionID,
		arg.CreatedAt,
	)
	return err
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT id, order_id, amount, method, status, transaction_id, refund_transaction_id, refund_reason, created_at
FROM payments
WHERE order_id = $1
`

func (q *Queries) GetPaymentByOrderID(ctx context.Context, orderID string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByOrderID, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.TransactionID,
		&i.RefundTransactionID,
		&i.RefundReason,
		&i.CreatedAt,
	)
	return i, err
}

const markPaymentRefunded = `-- name: MarkPaymentRefunded :execrows
UPDATE payments
SET status = $1, refund_transaction_id = $2, refund_reason = $3
WHERE order_id = $4
  AND status = $5
`

type MarkPaymentRefundedParams struct {
	Status              string         `json:"status"`
	RefundTransactionID sql.NullString `json:"refund_transaction_id"`
	RefundReason        sql.NullString `json:"refund_reason"`
	OrderID             string         `json:"order_id"`
	Status_2            string         `json:"status_2"`
}

func (q *Queries) MarkPaymentRefunded(ctx context.Context, arg MarkPaymentRefundedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markPaymentRefunded,
		arg.Status,
		arg.RefundTransactionID,
		arg.RefundReason,
		arg.OrderID,
		arg.Status_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
