// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: couriers.sql

package db

import (
	"context"
)

const countCouriers = `-- name: CountCouriers :one
SELECT COUNT(*)::bigint AS count
FROM couriers
`

func (q *Queries) CountCouriers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCouriers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCourier = `-- name: CreateCourier :exec
INSERT INTO couriers (id, name, status, latitude, longitude)
VALUES ($1, $2, $3, $4, $5)
`

type CreateCourierParams struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Status    string  `json:"status"`
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

func (q *Queries) CreateCourier(ctx context.Context, arg CreateCourierParams) error {
	_, err := q.db.ExecContext(ctx, createCourier,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.Latitude,
		arg.Longitude,
	)
	return err
}

const findAvailableCourier = `-- name: FindAvailableCourier :one
SELECT id, name, status, latitude, longitude
FROM couriers
WHERE status = $1
LIMIT 1
`

func (q *Queries) FindAvailableCourier(ctx context.Context, status string) (Courier, error) {
	row := q.db.QueryRowContext(ctx, findAvailableCourier, status)
	var i Courier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const listCouriers = `-- name: ListCouriers :many
SELECT id, name, status, latitude, longitude
FROM couriers
`

func (q *Queries) ListCouriers(ctx context.Context) ([]Courier, error) {
	rows, err := q.db.QueryContext(ctx, listCouriers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Courier{}
	for rows.Next() {
		var i Courier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCourierStatus = `-- name: SetCourierStatus :exec
UPDATE couriers
SET status = $1
WHERE id = $2
`

type SetCourierStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) SetCourierStatus(ctx context.Context, arg SetCourierStatusParams) error {
	_, err := q.db.ExecContext(ctx, setCourierStatus, arg.Status, arg.ID)
	return err
}
